### ISSUE TITLE
downloads.rport.io down

### ISSUE THREAD

**Issue by killisch** [realvnc-labs/rport-pairing#22]
https://download.rport.io/tacoscript/stable/ 
fails to load. 
unable to install client.

![image](https://user-images.githubusercontent.com/8190047/226779108-161f5a8f-1ebe-454e-b6b1-7ccfa86d7d14.png)

**Comment by thorstenkramm** [comment]
@killisch Thank you very much for bringing this issue to our attention. 
We fixed it.
