### ISSUE TITLE
Client Auto-Registration

### ISSUE THREAD

**Issue by iamsakthig** [realvnc-labs/rport-pairing#31]
In RPort documentation ( https://kb.rport.io/what-is-rport/features-and-benefits-of-rport/full-feature-list) in section "Client installation", it has been mentioned that Auto-Registration will be possible in the Rport "Clients do auto-registration. You can install the client directly on the remote machine without creating a configuration or a unique id on the server first. This makes mass deployment fast and comfortable."

Can you explain how this can be done ?  Please provide more details on this ?

We are planning to use Linux Mint as OS for Mass deployment. You can assume 100 to 500 Devices on a site.

**Comment by iamsakthig** [comment]
Can you please let me know if you have any inputs for me

**Comment by thorstenkramm** [comment]
@iamsakthig I created a small documentation [here](https://kb.rport.io/digging-deeper/using-the-api/create-client-credentials).

**Comment by iamsakthig** [comment]
Dear 


I am getting below error 

Systemd service already present.
A /etc/sudoers.d/rport-update-status has been created. Please review and change to your needs.
A /etc/sudoers.d/rport-all-cmd has been created. Please review and change to your needs.
tacoscript
Tacoscript installed taco version Version: 0.3.0
Build time: 2023-04-20T13:46:29Z
Git commit: cc703870d5ff4763a6da2e56670af8d2755b4fea
2023/05/31 10:15:47 error: client: connection error: websocket: bad handshake - Server maybe busy. Also check your client credentials AND check for tranparent proxies

#
# -------------!!   ERROR  !!-------------
#
# Installation of rport finished with errors.
#

Try the following to investigate:
1) systemctl rport status

2) tail /var/log/rport/rport.log

3) Ask for help on https://kb.rport.io/need-help/request-support



tail /var/log/rport/rport.log
2023/05/31 10:15:47 error: client: connection error: websocket: bad handshake - Server maybe busy. Also check your client credentials AND check for tranparent proxies
2023/05/31 10:15:47 info: client: Retrying in 5.000000025s...
2023/05/31 10:15:52 info: client: Trying to connect to ws://tmgu6nqvcss0.users.rport.io:80 ...
2023/05/31 10:15:52 info: client: Will wait up to 300.00 seconds for the server to respond
2023/05/31 10:15:53 error: client: connection error: websocket: bad handshake - Server maybe busy. Also check your client credentials AND check for tranparent proxies (attempt: 1 of infinite)
2023/05/31 10:15:53 info: client: Retrying in 5.421112291s...
2023/05/31 10:15:59 info: client: Trying to connect to ws://tmgu6nqvcss0.users.rport.io:80 ...
2023/05/31 10:15:59 info: client: Will wait up to 300.00 seconds for the server to respond
2023/05/31 10:16:00 error: client: connection error: websocket: bad handshake - Server maybe busy. Also check your client credentials AND check for tranparent proxies (attempt: 2 of infinite)
2023/05/31 10:16:00 info: client: Retrying in 16.92978147s...


THANKS G.SAKTHIVEL 

    On Friday, May 26, 2023 at 05:47:05 PM GMT+5:30, Thorsten Kramm ***@***.***> wrote:  
 
 


@iamsakthig I created a small documentation here.

**Comment by thorstenkramm** [comment]
@iamsakthig Did you check for transparent proxies and firewall settings?

PS: Whenever possible, please **do not respond via email**. Use your browser. Messages are cleaner and better readable.

**Comment by thorstenkramm** [comment]
Did you check your firewall? Is there a transparent proxy playing man in the middle?

**Comment by iamsakthig** [comment]
Firewall is not blocking.  I confirmed  this by adding two Ubuntu PCs. Is there still issue when connecting from Mint Linux ?

**Comment by thorstenkramm** [comment]
@iamsakthig Your issue is not related to Mint. The rport software has been installed and configured properly. The log claims, that the rport client cannot connect to the server due to network issues.
